// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: recordscores.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RecordScoreService_GetScore_FullMethodName = "/recordscores.RecordScoreService/GetScore"
)

// RecordScoreServiceClient is the client API for RecordScoreService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RecordScoreServiceClient interface {
	GetScore(ctx context.Context, in *GetScoreRequest, opts ...grpc.CallOption) (*GetScoreResponse, error)
}

type recordScoreServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRecordScoreServiceClient(cc grpc.ClientConnInterface) RecordScoreServiceClient {
	return &recordScoreServiceClient{cc}
}

func (c *recordScoreServiceClient) GetScore(ctx context.Context, in *GetScoreRequest, opts ...grpc.CallOption) (*GetScoreResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetScoreResponse)
	err := c.cc.Invoke(ctx, RecordScoreService_GetScore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RecordScoreServiceServer is the server API for RecordScoreService service.
// All implementations should embed UnimplementedRecordScoreServiceServer
// for forward compatibility.
type RecordScoreServiceServer interface {
	GetScore(context.Context, *GetScoreRequest) (*GetScoreResponse, error)
}

// UnimplementedRecordScoreServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRecordScoreServiceServer struct{}

func (UnimplementedRecordScoreServiceServer) GetScore(context.Context, *GetScoreRequest) (*GetScoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetScore not implemented")
}
func (UnimplementedRecordScoreServiceServer) testEmbeddedByValue() {}

// UnsafeRecordScoreServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RecordScoreServiceServer will
// result in compilation errors.
type UnsafeRecordScoreServiceServer interface {
	mustEmbedUnimplementedRecordScoreServiceServer()
}

func RegisterRecordScoreServiceServer(s grpc.ServiceRegistrar, srv RecordScoreServiceServer) {
	// If the following call pancis, it indicates UnimplementedRecordScoreServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RecordScoreService_ServiceDesc, srv)
}

func _RecordScoreService_GetScore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetScoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordScoreServiceServer).GetScore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecordScoreService_GetScore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordScoreServiceServer).GetScore(ctx, req.(*GetScoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RecordScoreService_ServiceDesc is the grpc.ServiceDesc for RecordScoreService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RecordScoreService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "recordscores.RecordScoreService",
	HandlerType: (*RecordScoreServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetScore",
			Handler:    _RecordScoreService_GetScore_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "recordscores.proto",
}
