// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: recordscores.proto

package proto

import (
	proto "github.com/brotherlogic/recordcollection/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ScoreAdjustment_AdjustmentType int32

const (
	ScoreAdjustment_IGNORED_ADJUSTMENT          ScoreAdjustment_AdjustmentType = 0
	ScoreAdjustment_OTHER_VERSIONS_ADJUSTMENT   ScoreAdjustment_AdjustmentType = 1
	ScoreAdjustment_DIGITAL_VERSIONS_ADJUSTMENT ScoreAdjustment_AdjustmentType = 2
	ScoreAdjustment_OWN_OTHER_ADJUSTMENT        ScoreAdjustment_AdjustmentType = 3
	ScoreAdjustment_PREVIOUSY_SOLD_ADJUSTMENT   ScoreAdjustment_AdjustmentType = 4
	ScoreAdjustment_KEEP_ADJUSTMENT             ScoreAdjustment_AdjustmentType = 5
	ScoreAdjustment_UNKNOWN_KEEP_ADJUSTMENT     ScoreAdjustment_AdjustmentType = 6
)

// Enum value maps for ScoreAdjustment_AdjustmentType.
var (
	ScoreAdjustment_AdjustmentType_name = map[int32]string{
		0: "IGNORED_ADJUSTMENT",
		1: "OTHER_VERSIONS_ADJUSTMENT",
		2: "DIGITAL_VERSIONS_ADJUSTMENT",
		3: "OWN_OTHER_ADJUSTMENT",
		4: "PREVIOUSY_SOLD_ADJUSTMENT",
		5: "KEEP_ADJUSTMENT",
		6: "UNKNOWN_KEEP_ADJUSTMENT",
	}
	ScoreAdjustment_AdjustmentType_value = map[string]int32{
		"IGNORED_ADJUSTMENT":          0,
		"OTHER_VERSIONS_ADJUSTMENT":   1,
		"DIGITAL_VERSIONS_ADJUSTMENT": 2,
		"OWN_OTHER_ADJUSTMENT":        3,
		"PREVIOUSY_SOLD_ADJUSTMENT":   4,
		"KEEP_ADJUSTMENT":             5,
		"UNKNOWN_KEEP_ADJUSTMENT":     6,
	}
)

func (x ScoreAdjustment_AdjustmentType) Enum() *ScoreAdjustment_AdjustmentType {
	p := new(ScoreAdjustment_AdjustmentType)
	*p = x
	return p
}

func (x ScoreAdjustment_AdjustmentType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ScoreAdjustment_AdjustmentType) Descriptor() protoreflect.EnumDescriptor {
	return file_recordscores_proto_enumTypes[0].Descriptor()
}

func (ScoreAdjustment_AdjustmentType) Type() protoreflect.EnumType {
	return &file_recordscores_proto_enumTypes[0]
}

func (x ScoreAdjustment_AdjustmentType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ScoreAdjustment_AdjustmentType.Descriptor instead.
func (ScoreAdjustment_AdjustmentType) EnumDescriptor() ([]byte, []int) {
	return file_recordscores_proto_rawDescGZIP(), []int{3, 0}
}

type Scores struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Scores        []*Score                 `protobuf:"bytes,1,rep,name=scores,proto3" json:"scores,omitempty"`
	LastScore     map[int32]*ComputedScore `protobuf:"bytes,2,rep,name=last_score,json=lastScore,proto3" json:"last_score,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Scores) Reset() {
	*x = Scores{}
	mi := &file_recordscores_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Scores) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Scores) ProtoMessage() {}

func (x *Scores) ProtoReflect() protoreflect.Message {
	mi := &file_recordscores_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Scores.ProtoReflect.Descriptor instead.
func (*Scores) Descriptor() ([]byte, []int) {
	return file_recordscores_proto_rawDescGZIP(), []int{0}
}

func (x *Scores) GetScores() []*Score {
	if x != nil {
		return x.Scores
	}
	return nil
}

func (x *Scores) GetLastScore() map[int32]*ComputedScore {
	if x != nil {
		return x.LastScore
	}
	return nil
}

type Score struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	InstanceId    int32                           `protobuf:"varint,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Rating        int32                           `protobuf:"varint,2,opt,name=rating,proto3" json:"rating,omitempty"`
	Category      proto.ReleaseMetadata_Category  `protobuf:"varint,3,opt,name=category,proto3,enum=recordcollection.ReleaseMetadata_Category" json:"category,omitempty"`
	ScoreTime     int64                           `protobuf:"varint,4,opt,name=score_time,json=scoreTime,proto3" json:"score_time,omitempty"`
	Keep          proto.ReleaseMetadata_KeepState `protobuf:"varint,5,opt,name=keep,proto3,enum=recordcollection.ReleaseMetadata_KeepState" json:"keep,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Score) Reset() {
	*x = Score{}
	mi := &file_recordscores_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Score) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Score) ProtoMessage() {}

func (x *Score) ProtoReflect() protoreflect.Message {
	mi := &file_recordscores_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Score.ProtoReflect.Descriptor instead.
func (*Score) Descriptor() ([]byte, []int) {
	return file_recordscores_proto_rawDescGZIP(), []int{1}
}

func (x *Score) GetInstanceId() int32 {
	if x != nil {
		return x.InstanceId
	}
	return 0
}

func (x *Score) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *Score) GetCategory() proto.ReleaseMetadata_Category {
	if x != nil {
		return x.Category
	}
	return proto.ReleaseMetadata_Category(0)
}

func (x *Score) GetScoreTime() int64 {
	if x != nil {
		return x.ScoreTime
	}
	return 0
}

func (x *Score) GetKeep() proto.ReleaseMetadata_KeepState {
	if x != nil {
		return x.Keep
	}
	return proto.ReleaseMetadata_KeepState(0)
}

type ComputedScore struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BaseRating    int32                  `protobuf:"varint,1,opt,name=base_rating,json=baseRating,proto3" json:"base_rating,omitempty"`
	Adjustments   []*ScoreAdjustment     `protobuf:"bytes,2,rep,name=adjustments,proto3" json:"adjustments,omitempty"`
	Overall       float32                `protobuf:"fixed32,3,opt,name=overall,proto3" json:"overall,omitempty"`
	CurrFolder    int32                  `protobuf:"varint,4,opt,name=curr_folder,json=currFolder,proto3" json:"curr_folder,omitempty"`
	Location      proto.PurchaseLocation `protobuf:"varint,5,opt,name=location,proto3,enum=recordcollection.PurchaseLocation" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComputedScore) Reset() {
	*x = ComputedScore{}
	mi := &file_recordscores_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComputedScore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComputedScore) ProtoMessage() {}

func (x *ComputedScore) ProtoReflect() protoreflect.Message {
	mi := &file_recordscores_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComputedScore.ProtoReflect.Descriptor instead.
func (*ComputedScore) Descriptor() ([]byte, []int) {
	return file_recordscores_proto_rawDescGZIP(), []int{2}
}

func (x *ComputedScore) GetBaseRating() int32 {
	if x != nil {
		return x.BaseRating
	}
	return 0
}

func (x *ComputedScore) GetAdjustments() []*ScoreAdjustment {
	if x != nil {
		return x.Adjustments
	}
	return nil
}

func (x *ComputedScore) GetOverall() float32 {
	if x != nil {
		return x.Overall
	}
	return 0
}

func (x *ComputedScore) GetCurrFolder() int32 {
	if x != nil {
		return x.CurrFolder
	}
	return 0
}

func (x *ComputedScore) GetLocation() proto.PurchaseLocation {
	if x != nil {
		return x.Location
	}
	return proto.PurchaseLocation(0)
}

type ScoreAdjustment struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Type          ScoreAdjustment_AdjustmentType `protobuf:"varint,1,opt,name=type,proto3,enum=recordscores.ScoreAdjustment_AdjustmentType" json:"type,omitempty"`
	ValueChange   float32                        `protobuf:"fixed32,2,opt,name=value_change,json=valueChange,proto3" json:"value_change,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScoreAdjustment) Reset() {
	*x = ScoreAdjustment{}
	mi := &file_recordscores_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoreAdjustment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoreAdjustment) ProtoMessage() {}

func (x *ScoreAdjustment) ProtoReflect() protoreflect.Message {
	mi := &file_recordscores_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoreAdjustment.ProtoReflect.Descriptor instead.
func (*ScoreAdjustment) Descriptor() ([]byte, []int) {
	return file_recordscores_proto_rawDescGZIP(), []int{3}
}

func (x *ScoreAdjustment) GetType() ScoreAdjustment_AdjustmentType {
	if x != nil {
		return x.Type
	}
	return ScoreAdjustment_IGNORED_ADJUSTMENT
}

func (x *ScoreAdjustment) GetValueChange() float32 {
	if x != nil {
		return x.ValueChange
	}
	return 0
}

type GetScoreRequest struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	InstanceId    int32                          `protobuf:"varint,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Category      proto.ReleaseMetadata_Category `protobuf:"varint,2,opt,name=category,proto3,enum=recordcollection.ReleaseMetadata_Category" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetScoreRequest) Reset() {
	*x = GetScoreRequest{}
	mi := &file_recordscores_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetScoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScoreRequest) ProtoMessage() {}

func (x *GetScoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recordscores_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScoreRequest.ProtoReflect.Descriptor instead.
func (*GetScoreRequest) Descriptor() ([]byte, []int) {
	return file_recordscores_proto_rawDescGZIP(), []int{4}
}

func (x *GetScoreRequest) GetInstanceId() int32 {
	if x != nil {
		return x.InstanceId
	}
	return 0
}

func (x *GetScoreRequest) GetCategory() proto.ReleaseMetadata_Category {
	if x != nil {
		return x.Category
	}
	return proto.ReleaseMetadata_Category(0)
}

type GetScoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scores        []*Score               `protobuf:"bytes,1,rep,name=scores,proto3" json:"scores,omitempty"`
	ComputedScore *ComputedScore         `protobuf:"bytes,2,opt,name=computed_score,json=computedScore,proto3" json:"computed_score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetScoreResponse) Reset() {
	*x = GetScoreResponse{}
	mi := &file_recordscores_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetScoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScoreResponse) ProtoMessage() {}

func (x *GetScoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_recordscores_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScoreResponse.ProtoReflect.Descriptor instead.
func (*GetScoreResponse) Descriptor() ([]byte, []int) {
	return file_recordscores_proto_rawDescGZIP(), []int{5}
}

func (x *GetScoreResponse) GetScores() []*Score {
	if x != nil {
		return x.Scores
	}
	return nil
}

func (x *GetScoreResponse) GetComputedScore() *ComputedScore {
	if x != nil {
		return x.ComputedScore
	}
	return nil
}

var File_recordscores_proto protoreflect.FileDescriptor

const file_recordscores_proto_rawDesc = "" +
	"\n" +
	"\x12recordscores.proto\x12\frecordscores\x1aEgithub.com/brotherlogic/recordcollection/proto/recordcollection.proto\"\xd4\x01\n" +
	"\x06Scores\x12+\n" +
	"\x06scores\x18\x01 \x03(\v2\x13.recordscores.ScoreR\x06scores\x12B\n" +
	"\n" +
	"last_score\x18\x02 \x03(\v2#.recordscores.Scores.LastScoreEntryR\tlastScore\x1aY\n" +
	"\x0eLastScoreEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x121\n" +
	"\x05value\x18\x02 \x01(\v2\x1b.recordscores.ComputedScoreR\x05value:\x028\x01\"\xe8\x01\n" +
	"\x05Score\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\x05R\n" +
	"instanceId\x12\x16\n" +
	"\x06rating\x18\x02 \x01(\x05R\x06rating\x12F\n" +
	"\bcategory\x18\x03 \x01(\x0e2*.recordcollection.ReleaseMetadata.CategoryR\bcategory\x12\x1d\n" +
	"\n" +
	"score_time\x18\x04 \x01(\x03R\tscoreTime\x12?\n" +
	"\x04keep\x18\x05 \x01(\x0e2+.recordcollection.ReleaseMetadata.KeepStateR\x04keep\"\xec\x01\n" +
	"\rComputedScore\x12\x1f\n" +
	"\vbase_rating\x18\x01 \x01(\x05R\n" +
	"baseRating\x12?\n" +
	"\vadjustments\x18\x02 \x03(\v2\x1d.recordscores.ScoreAdjustmentR\vadjustments\x12\x18\n" +
	"\aoverall\x18\x03 \x01(\x02R\aoverall\x12\x1f\n" +
	"\vcurr_folder\x18\x04 \x01(\x05R\n" +
	"currFolder\x12>\n" +
	"\blocation\x18\x05 \x01(\x0e2\".recordcollection.PurchaseLocationR\blocation\"\xcc\x02\n" +
	"\x0fScoreAdjustment\x12@\n" +
	"\x04type\x18\x01 \x01(\x0e2,.recordscores.ScoreAdjustment.AdjustmentTypeR\x04type\x12!\n" +
	"\fvalue_change\x18\x02 \x01(\x02R\vvalueChange\"\xd3\x01\n" +
	"\x0eAdjustmentType\x12\x16\n" +
	"\x12IGNORED_ADJUSTMENT\x10\x00\x12\x1d\n" +
	"\x19OTHER_VERSIONS_ADJUSTMENT\x10\x01\x12\x1f\n" +
	"\x1bDIGITAL_VERSIONS_ADJUSTMENT\x10\x02\x12\x18\n" +
	"\x14OWN_OTHER_ADJUSTMENT\x10\x03\x12\x1d\n" +
	"\x19PREVIOUSY_SOLD_ADJUSTMENT\x10\x04\x12\x13\n" +
	"\x0fKEEP_ADJUSTMENT\x10\x05\x12\x1b\n" +
	"\x17UNKNOWN_KEEP_ADJUSTMENT\x10\x06\"z\n" +
	"\x0fGetScoreRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\x05R\n" +
	"instanceId\x12F\n" +
	"\bcategory\x18\x02 \x01(\x0e2*.recordcollection.ReleaseMetadata.CategoryR\bcategory\"\x83\x01\n" +
	"\x10GetScoreResponse\x12+\n" +
	"\x06scores\x18\x01 \x03(\v2\x13.recordscores.ScoreR\x06scores\x12B\n" +
	"\x0ecomputed_score\x18\x02 \x01(\v2\x1b.recordscores.ComputedScoreR\rcomputedScore2a\n" +
	"\x12RecordScoreService\x12K\n" +
	"\bGetScore\x12\x1d.recordscores.GetScoreRequest\x1a\x1e.recordscores.GetScoreResponse\"\x00B,Z*github.com/brotherlogic/recordscores/protob\x06proto3"

var (
	file_recordscores_proto_rawDescOnce sync.Once
	file_recordscores_proto_rawDescData []byte
)

func file_recordscores_proto_rawDescGZIP() []byte {
	file_recordscores_proto_rawDescOnce.Do(func() {
		file_recordscores_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_recordscores_proto_rawDesc), len(file_recordscores_proto_rawDesc)))
	})
	return file_recordscores_proto_rawDescData
}

var file_recordscores_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_recordscores_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_recordscores_proto_goTypes = []any{
	(ScoreAdjustment_AdjustmentType)(0),  // 0: recordscores.ScoreAdjustment.AdjustmentType
	(*Scores)(nil),                       // 1: recordscores.Scores
	(*Score)(nil),                        // 2: recordscores.Score
	(*ComputedScore)(nil),                // 3: recordscores.ComputedScore
	(*ScoreAdjustment)(nil),              // 4: recordscores.ScoreAdjustment
	(*GetScoreRequest)(nil),              // 5: recordscores.GetScoreRequest
	(*GetScoreResponse)(nil),             // 6: recordscores.GetScoreResponse
	nil,                                  // 7: recordscores.Scores.LastScoreEntry
	(proto.ReleaseMetadata_Category)(0),  // 8: recordcollection.ReleaseMetadata.Category
	(proto.ReleaseMetadata_KeepState)(0), // 9: recordcollection.ReleaseMetadata.KeepState
	(proto.PurchaseLocation)(0),          // 10: recordcollection.PurchaseLocation
}
var file_recordscores_proto_depIdxs = []int32{
	2,  // 0: recordscores.Scores.scores:type_name -> recordscores.Score
	7,  // 1: recordscores.Scores.last_score:type_name -> recordscores.Scores.LastScoreEntry
	8,  // 2: recordscores.Score.category:type_name -> recordcollection.ReleaseMetadata.Category
	9,  // 3: recordscores.Score.keep:type_name -> recordcollection.ReleaseMetadata.KeepState
	4,  // 4: recordscores.ComputedScore.adjustments:type_name -> recordscores.ScoreAdjustment
	10, // 5: recordscores.ComputedScore.location:type_name -> recordcollection.PurchaseLocation
	0,  // 6: recordscores.ScoreAdjustment.type:type_name -> recordscores.ScoreAdjustment.AdjustmentType
	8,  // 7: recordscores.GetScoreRequest.category:type_name -> recordcollection.ReleaseMetadata.Category
	2,  // 8: recordscores.GetScoreResponse.scores:type_name -> recordscores.Score
	3,  // 9: recordscores.GetScoreResponse.computed_score:type_name -> recordscores.ComputedScore
	3,  // 10: recordscores.Scores.LastScoreEntry.value:type_name -> recordscores.ComputedScore
	5,  // 11: recordscores.RecordScoreService.GetScore:input_type -> recordscores.GetScoreRequest
	6,  // 12: recordscores.RecordScoreService.GetScore:output_type -> recordscores.GetScoreResponse
	12, // [12:13] is the sub-list for method output_type
	11, // [11:12] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_recordscores_proto_init() }
func file_recordscores_proto_init() {
	if File_recordscores_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_recordscores_proto_rawDesc), len(file_recordscores_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_recordscores_proto_goTypes,
		DependencyIndexes: file_recordscores_proto_depIdxs,
		EnumInfos:         file_recordscores_proto_enumTypes,
		MessageInfos:      file_recordscores_proto_msgTypes,
	}.Build()
	File_recordscores_proto = out.File
	file_recordscores_proto_goTypes = nil
	file_recordscores_proto_depIdxs = nil
}
